### ISSUE TITLE
[BUG] - Need ability to control ordering of headshots in the Leadership block on the About Us page

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#199] opened 2022-06-13 18:14 UTC
### What site is this for?

Quansight LLC

### Actual behavior

We will require the functionality to control the ordering of the display of the team members listed in the `all` variant of the Team component, used to populate the Leadership Team section of the About Us page. E.g., at minimum, we will want to reorder so that Travis and Matt are the first two people displayed.

![image](https://user-images.githubusercontent.com/11325439/173417784-024c583c-95fc-4b62-951f-8b1478dd0794.png)

**Comment by trallard** [comment] 2022-06-14 20:53
AFAIK you can order the entries in Storyblock and the items will display in such order. 

cc /@noatamir who might be able to confirm since this was true for Labs

**Comment by noatamir** [comment] 2022-06-14 21:21
I can confirm re-ordering works for LLC. 

I just changed the order of the first 5 people to be:
Travis, Matt, Tania, Ralf, Dhavide. 

Closing this and will pick it up on slack tomorrow async with @bskinn

**Closed by noatamir** 2022-06-14 21:21 UTC
Labels: type: bug 🐛, LLC 🤝, area: Storyblok, area: launch 🚀
