### ISSUE TITLE
[BUG] - Preview bar is clipping the hero images, affects blog workflow

### ISSUE THREAD

**Issue by noatamir** [Quansight/Quansight-website#555] opened 2022-11-03 11:49 UTC
### What site is this for?

Quansight Labs

### Expected behavior

@gabalafou  Can we have the preview bar push the whole website down and not just the black bar "above the hero image"? This is misleading for contributors to the blog.

The live blog hero image isn't clipped:
<img width="1456" alt="Screenshot of the same blog live on the website, the hero is not cropped by the black bar" src="https://user-images.githubusercontent.com/6564007/199712967-1597df24-eae4-4a0d-9d35-ca00891550e1.png">

### Actual behavior

The preview blog hero image is clipped. Possibly due to the added preview bar?
<img width="1457" alt="Screenshot of blog in preview mode with cropped hero image" src="https://user-images.githubusercontent.com/6564007/199712586-e521c33a-7cc9-4045-8edc-323a60bd3da9.png">

**Comment by gabalafou** [comment] 2022-11-03 12:03
That’s what I originally tried to do, but I couldn’t figure out how, and I didn’t want to spend a lot of time on it, so I gave up.El nov. 3, 2022, a la(s) 06:49, Noa Tamir ***@***.***> escribió:﻿
What site is this for?
Quansight Labs
Expected behavior
@gabalafou  Can we have the preview bar push the whole website down and not just the black bar "above the hero image"? This is misleading for contributors to the blog.

Actual behavior

How to Reproduce the problem?
No response
Anything else?
No response

**Comment by noatamir** [comment] 2022-11-03 13:25
I see. Is it ok if we keep this as a `low priority` bug, so I can link to it from the readme for context on the behavior? Or would you rather close this as a `won't fix`?

**Comment by gabalafou** [comment] 2022-11-03 13:26
No I think it's good to have the issue documented, thank you!

**Comment by bskinn** [comment] 2023-05-30 10:27
@gabalafou, I believe your change to the preview-mode banner now makes this issue obsolete. Should we close?

**Comment by gabalafou** [comment] 2023-05-30 10:29
Yep, closing now.

**Comment by bskinn** [comment] 2023-05-30 10:29
Is there documentation in README that needs to be updated?

**Closed by gabalafou** 2023-05-30 10:29 UTC
Labels: type: bug 🐛, labs 🔭, consulting 🤝, owner: Quansight

**Comment by gabalafou** [comment] 2023-05-30 10:32
Yes, good point, because it's not a banner anymore. I'll just do a quick and dirty search-replace of "banner" for "overlay"

**Comment by gabalafou** [comment] 2023-05-30 10:40
https://github.com/Quansight/Quansight-website/pull/735
